pipeline:
  identifier: Build_Hariharnath007_Jenkins_Zero_To_Hero_1767133243957
  name: Build Jenkins-Zero-To-Hero
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Hariharnath007/Jenkins-Zero-To-Hero
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: git-checkout
                  identifier: gitcheckout
                  spec:
                    shell: Sh
                    command: |-
                      'echo passed'
                      //git branch: 'main', url: 'https://github.com/Hariharnath007/Jenkins-Zero-To-Hero.git'
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: maven build and test
                  identifier: maven_build_and_test
                  spec:
                    shell: Sh
                    command: |-
                      sh 'ls -ltr'
                              // build the project and create a JAR file
                      sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
    - stage:
        name: Static Code Analysis
        identifier: Static_Code_Analysis
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: sonar scan
                  identifier: sonar_scan
                  spec:
                    shell: Sh
                    command: |-
                      environment {
                              SONAR_URL = "http://54.209.253.70:9000/"
                            }
                            steps {
                              withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                                sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                              }
                            }
  tags: {}
